import type { Metadata } from "next";
import { Bebas_Neue, Montserrat } from 'next/font/google';
import "./globals.css";
import Head from "next/head";


const bebasNeue = Bebas_Neue({
  weight: '400',
  subsets: ['latin']
});

const montserrat = Montserrat({
  weight: '400',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const jsonLdData = {
    "@context": "https://schema.org",
    "@type": "SportsEvent",
    "name": "Arena del Valle: Noche de Lucha Libre",
    "startDate": "2025-09-20T20:00",
    "location": {
      "@type": "Place",
      "name": "Arena del Valle",
      "address": "Ecatepec, México",
    },
    "performer": {
      "@type": "Person",
      "name": "Penta El Cero Miedo",
    },
    "url": "https://arena-del-valle-site.vercel.app",
  };

  return (
    <html lang="es">
      <Head>
        <meta
          name="google-site-verification"
          content="jKfupuO5iLvmHnRr2M1_cimO3l_qgR4baHyALDohNmc"
        />
      </Head>
      <body
        className={`${bebasNeue.className} ${montserrat.className} antialiased`}
      >
        {children}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLdData) }}
        />
      </body>
    </html>
  );
}
