import type { Metadata } from "next";
import { Bebas_Neue, Montserrat } from 'next/font/google';
import "./globals.css";


const bebasNeue = Bebas_Neue({
  weight: '400',
  subsets: ['latin']
});

const montserrat = Montserrat({
  weight: '400',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bebasNeue.className} ${montserrat.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
